// Writes src/data/images.ts from IMAGE-MANIFEST.json and which masters are on disk.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const manifest = JSON.parse(readFileSync(new URL("../IMAGE-MANIFEST.json", import.meta.url), "utf8"));

function aspect(raw) {
  const match = String(raw).match(/(\d+)\s*:\s*(\d+)/);
  return match ? `${match[1]}/${match[2]}` : "4/3";
}

function readyFor(publicPath) {
  const rel = publicPath.replace(/^\//, "");
  const abs = path.join("public", rel);
  if (existsSync(abs)) return true;
  const base = abs.replace(/\.(jpe?g|png|webp)$/i, "");
  return [480, 800, 1200, 1600].some((w) => existsSync(`${base}-${w}.avif`) || existsSync(`${base}-${w}.webp`));
}

function widthsFor(publicPath) {
  const rel = publicPath.replace(/^\//, "").replace(/\.(jpe?g|png|webp)$/i, "");
  return [480, 800, 1200, 1600].filter((w) => existsSync(path.join("public", `${rel}-${w}.avif`)));
}

const cards = manifest.cards.map((card) => ({
  route: card.route,
  base: card.image.replace(/\.(jpe?g|png|webp)$/i, ""),
  alt: card.alt,
  aspect: aspect(card.aspect_master),
  focal: card.hub === "hub-hero" ? "32% center" : "center 40%",
  hub: card.hub,
  label: card.label,
  title: card.card_title,
  ready: readyFor(card.image),
  srcset: widthsFor(card.image).length > 0,
  widths: widthsFor(card.image),
}));

cards.unshift({
  route: "/",
  base: "/images/home-hero",
  alt: "Overcast forest switchbacks and damp rock, with no gear logos",
  aspect: "16/9",
  focal: "center 45%",
  hub: "home",
  label: "Home",
  title: "Home",
  ready: readyFor("/images/home-hero.jpg"),
  srcset: widthsFor("/images/home-hero.jpg").length > 0,
  widths: widthsFor("/images/home-hero.jpg"),
});

const extras = [
  ["tents-freestanding-vs-pole", "16/9", "A freestanding dome tent on a wooden platform beside a trekking-pole shelter on dirt, same forest light"],
  ["tents-vestibule-rain", "4/3", "A tent vestibule in steady rain with a pack tucked under the fly, no logos"],
  ["boots-toebox-topdown", "4/3", "Top-down view of a wide toe box hiking boot on wet rock, laces loose, no logo"],
  ["boots-lacing-heel", "4/3", "Hands lacing a mid hiking boot on a muddy trail, heel locked, no faces"],
  ["rain-pitzip-open", "4/3", "A matte rain shell with a pit zip open, seen from the side in drizzle, no logo"],
  ["rain-hood-brim", "4/3", "A rain jacket hood brim in steady rain, wearer seen from behind, no face"],
  ["overnight-camp-dusk", "16/9", "A small tent and pack at a wooded trailhead at blue hour, first overnight kit"],
  ["overnight-kitchen-rock", "4/3", "A canister stove and pot on a flat rock beside a headlamp, blue hour, no logos"],
  ["pack-mesh-back-detail", "4/3", "Close view of a suspended mesh backpack panel on trailhead gravel, unbranded"],
  ["pack-lid-pockets-detail", "4/3", "Close view of a backpack lid and side pockets on trailhead gravel, unbranded"],
];
for (const [slug, aspect, alt] of extras) {
  const image = `/images/inline/${slug}.jpg`;
  cards.push({
    route: `/inline/${slug}`,
    base: image.replace(/\.(jpe?g|png|webp)$/i, ""),
    alt,
    aspect: aspect.replace(":", "/"),
    focal: "center 40%",
    hub: "inline",
    label: "Figure",
    title: slug,
    ready: readyFor(image),
    srcset: widthsFor(image).length > 0,
    widths: widthsFor(image),
  });
}

const body = `/* Generated by scripts/gen-images.mjs. Do not edit by hand. */
export type TkImageMeta = {
  route: string;
  base: string;
  alt: string;
  aspect: string;
  focal: string;
  hub: string;
  label: string;
  title: string;
  ready: boolean;
  srcset: boolean;
  widths: number[];
};

export const IMAGES: TkImageMeta[] = ${JSON.stringify(cards, null, 2)};

const BY_ROUTE = new Map(IMAGES.map((image) => [image.route, image]));

export function imageFor(route: string) {
  return BY_ROUTE.get(route);
}

export function ogCardPath(routePath: string) {
  if (routePath === "/") return "/og/home.jpg";
  return \`/og\${routePath}.jpg\`;
}
`;

writeFileSync(new URL("../src/data/images.ts", import.meta.url), body);
const ready = cards.filter((c) => c.ready).length;
console.log(`images.ts ${cards.length} routes, ${ready} ready`);
