/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BestIndexRouteImport } from './routes/best/index'
import { Route as BestSlugRouteImport } from './routes/best/$slug'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as GearIndexRouteImport } from './routes/gear/index'
import { Route as GearSlugRouteImport } from './routes/gear/$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as KitsIndexRouteImport } from './routes/kits/index'
import { Route as KitsSlugRouteImport } from './routes/kits/$slug'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BestIndexRoute = BestIndexRouteImport.update({
  id: '/best/',
  path: '/best/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSlugRoute = BestSlugRouteImport.update({
  id: '/best/$slug',
  path: '/best/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GearIndexRoute = GearIndexRouteImport.update({
  id: '/gear/',
  path: '/gear/',
  getParentRoute: () => rootRouteImport,
} as any)
const GearSlugRoute = GearSlugRouteImport.update({
  id: '/gear/$slug',
  path: '/gear/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsIndexRoute = KitsIndexRouteImport.update({
  id: '/kits/',
  path: '/kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsSlugRoute = KitsSlugRouteImport.update({
  id: '/kits/$slug',
  path: '/kits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/editorial': typeof EditorialRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/gear/$slug': typeof GearSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/kits/$slug': typeof KitsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/best/': typeof BestIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/gear/': typeof GearIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/kits/': typeof KitsIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/editorial': typeof EditorialRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/gear/$slug': typeof GearSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/kits/$slug': typeof KitsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/best': typeof BestIndexRoute
  '/compare': typeof CompareIndexRoute
  '/gear': typeof GearIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/kits': typeof KitsIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/editorial': typeof EditorialRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/gear/$slug': typeof GearSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/kits/$slug': typeof KitsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/best/': typeof BestIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/gear/': typeof GearIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/kits/': typeof KitsIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/contact'
    | '/disclosure'
    | '/editorial'
    | '/library'
    | '/privacy'
    | '/sitemap.xml'
    | '/best/$slug'
    | '/compare/$slug'
    | '/gear/$slug'
    | '/guides/$slug'
    | '/kits/$slug'
    | '/learn/$slug'
    | '/products/$slug'
    | '/best/'
    | '/compare/'
    | '/gear/'
    | '/guides/'
    | '/kits/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/contact'
    | '/disclosure'
    | '/editorial'
    | '/library'
    | '/privacy'
    | '/sitemap.xml'
    | '/best/$slug'
    | '/compare/$slug'
    | '/gear/$slug'
    | '/guides/$slug'
    | '/kits/$slug'
    | '/learn/$slug'
    | '/products/$slug'
    | '/best'
    | '/compare'
    | '/gear'
    | '/guides'
    | '/kits'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/contact'
    | '/disclosure'
    | '/editorial'
    | '/library'
    | '/privacy'
    | '/sitemap.xml'
    | '/best/$slug'
    | '/compare/$slug'
    | '/gear/$slug'
    | '/guides/$slug'
    | '/kits/$slug'
    | '/learn/$slug'
    | '/products/$slug'
    | '/best/'
    | '/compare/'
    | '/gear/'
    | '/guides/'
    | '/kits/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  EditorialRoute: typeof EditorialRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BestSlugRoute: typeof BestSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  GearSlugRoute: typeof GearSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  KitsSlugRoute: typeof KitsSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BestIndexRoute: typeof BestIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  GearIndexRoute: typeof GearIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  KitsIndexRoute: typeof KitsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best/': {
      id: '/best/'
      path: '/best'
      fullPath: '/best/'
      preLoaderRoute: typeof BestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best/$slug': {
      id: '/best/$slug'
      path: '/best/$slug'
      fullPath: '/best/$slug'
      preLoaderRoute: typeof BestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/': {
      id: '/gear/'
      path: '/gear'
      fullPath: '/gear/'
      preLoaderRoute: typeof GearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/$slug': {
      id: '/gear/$slug'
      path: '/gear/$slug'
      fullPath: '/gear/$slug'
      preLoaderRoute: typeof GearSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits/': {
      id: '/kits/'
      path: '/kits'
      fullPath: '/kits/'
      preLoaderRoute: typeof KitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits/$slug': {
      id: '/kits/$slug'
      path: '/kits/$slug'
      fullPath: '/kits/$slug'
      preLoaderRoute: typeof KitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  EditorialRoute: EditorialRoute,
  LibraryRoute: LibraryRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BestSlugRoute: BestSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  GearSlugRoute: GearSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  KitsSlugRoute: KitsSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BestIndexRoute: BestIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  GearIndexRoute: GearIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  KitsIndexRoute: KitsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
